version: 2.1

jobs:
  build:
    docker:
      - image: ruby:2.7

    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run: gem install bundler
      - run: bundle install

      # Run tests
      - run: bundle exec ruby test/main_test.rb
