version: 2.1

jobs:
  build:
    docker:
      - image: ruby:3.1.2

    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run: gem install bundler
      - run: bundle install

      # Run tests
      - run: bundle exec ruby rice_cooker_test.rb
