version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Restore Dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build

workflows:
  version: 2
  build:
    jobs:
      - build
